# Front end build
FROM node:24-alpine AS frontend
WORKDIR /app
RUN corepack enable
COPY web/package.json web/pnpm-lock.yaml ./web/
RUN cd web && pnpm install --frozen-lockfile
COPY . .
RUN cd web && pnpm run release

# Back end build
FROM golang:1.26.1-alpine AS backend
WORKDIR /app
RUN apk add --no-cache git ca-certificates
COPY go.mod go.sum ./
RUN go mod download
COPY . .
COPY --from=frontend /app/server/router/frontend/dist ./server/router/frontend/dist
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o memos ./cmd/memos

# Runtime stage
FROM alpine:3.23
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache ca-certificates tzdata && \
    addgroup -S appgroup && adduser -S appuser -G appgroup && \
    mkdir -p /var/opt/memos && \
    chown -R appuser:appgroup /var/opt/memos
WORKDIR /app
COPY --from=backend /app/memos ./

ENV MEMOS_PORT=5230

USER appuser

EXPOSE 5230

CMD ["./memos"]