name: App CI

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ecsmemos

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@10.33.4 --activate

      - name: Install dependencies
        working-directory: app/web
        run: pnpm install --frozen-lockfile

      - name: Lint
        working-directory: app/web
        run: pnpm run lint

      - name: Build frontend
        working-directory: app/web
        run: pnpm run release

      - name: Set image variables
        run: |
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI=${REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}

          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV


      - name: Build Docker image
        run: docker build -t "${IMAGE_URI}" ./app

      - name: Scan image with Grype
        uses: anchore/scan-action@v7
        with:
          image: ${{ env.IMAGE_URI }}
          fail-build: true
          severity-cutoff: high

      - name: Push image to ECR
        run: |
          docker push "${IMAGE_URI}"
         