name: Terraform Security Scan

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/security.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra
          framework: terraform
          soft_fail: true
          output_format: cli